// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8q4zgim0sG6l01xi90RdQi3irOqZN33o',
    appId: '1:1030396304590:web:dfe6a2be52ba5deeaa049f',
    messagingSenderId: '1030396304590',
    projectId: 'e-commerce-8da14',
    authDomain: 'e-commerce-8da14.firebaseapp.com',
    storageBucket: 'e-commerce-8da14.firebasestorage.app',
    measurementId: 'G-BGVY75FVNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcf-eYTKAQVcKnOkwwqyTaTWli-BS8o04',
    appId: '1:1030396304590:android:8a7e3effc106fa17aa049f',
    messagingSenderId: '1030396304590',
    projectId: 'e-commerce-8da14',
    storageBucket: 'e-commerce-8da14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCXO4TvtJmYyfl9lcaTdkb9lUtrJtE92M',
    appId: '1:1030396304590:ios:975a718c24958bceaa049f',
    messagingSenderId: '1030396304590',
    projectId: 'e-commerce-8da14',
    storageBucket: 'e-commerce-8da14.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );
}
